# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cameraservice/cameraservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/cameraservice/cameraservice.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'proto/cameraservice/cameraservice.proto\"=\n\rPictureConfig\x12,\n\x0b\x64\x61ta_format\x18\x01 \x01(\x0e\x32\x0b.DataFormatR\ndataFormat\"\x07\n\x05\x45mpty\"M\n\x0fPicturePointers\x12:\n\x10picture_pointers\x18\x01 \x03(\x0b\x32\x0f.PicturePointerR\x0fpicturePointers\"W\n\x07Picture\x12\x1b\n\tshot_time\x18\x01 \x01(\x03R\x08shotTime\x12\x12\n\x04\x64\x61ta\x18\x02 \x01(\x0cR\x04\x64\x61ta\x12\x1b\n\tfile_size\x18\x03 \x01(\x03R\x08\x66ileSize\"\"\n\x0ePicturePointer\x12\x10\n\x03uri\x18\x01 \x01(\tR\x03uri*0\n\nDataFormat\x12\x07\n\x03PNG\x10\x00\x12\x07\n\x03JPG\x10\x01\x12\x07\n\x03RAW\x10\x02\x12\x07\n\x03\x42MP\x10\x03\x32\x41\n\x12HardwareController\x12+\n\x0bTakePicture\x12\x0e.PictureConfig\x1a\x08.Picture\"\x00\x30\x01\x32\xcc\x01\n\x11ServiceController\x12\x30\n\x0bTakePicture\x12\x0e.PictureConfig\x1a\x0f.PicturePointer\"\x00\x12+\n\nGetPicture\x12\x0f.PicturePointer\x1a\x08.Picture\"\x00\x30\x01\x12*\n\rDeletePicture\x12\x0f.PicturePointer\x1a\x06.Empty\"\x00\x12,\n\x0eGetAllPictures\x12\x06.Empty\x1a\x10.PicturePointers\"\x00\x62\x06proto3'
)

_DATAFORMAT = _descriptor.EnumDescriptor(
  name='DataFormat',
  full_name='DataFormat',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PNG', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JPG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RAW', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BMP', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=319,
  serialized_end=367,
)
_sym_db.RegisterEnumDescriptor(_DATAFORMAT)

DataFormat = enum_type_wrapper.EnumTypeWrapper(_DATAFORMAT)
PNG = 0
JPG = 1
RAW = 2
BMP = 3



_PICTURECONFIG = _descriptor.Descriptor(
  name='PictureConfig',
  full_name='PictureConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_format', full_name='PictureConfig.data_format', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='dataFormat', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=104,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=113,
)


_PICTUREPOINTERS = _descriptor.Descriptor(
  name='PicturePointers',
  full_name='PicturePointers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='picture_pointers', full_name='PicturePointers.picture_pointers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='picturePointers', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=192,
)


_PICTURE = _descriptor.Descriptor(
  name='Picture',
  full_name='Picture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shot_time', full_name='Picture.shot_time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='shotTime', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='Picture.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='data', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_size', full_name='Picture.file_size', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='fileSize', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=281,
)


_PICTUREPOINTER = _descriptor.Descriptor(
  name='PicturePointer',
  full_name='PicturePointer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='PicturePointer.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='uri', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=317,
)

_PICTURECONFIG.fields_by_name['data_format'].enum_type = _DATAFORMAT
_PICTUREPOINTERS.fields_by_name['picture_pointers'].message_type = _PICTUREPOINTER
DESCRIPTOR.message_types_by_name['PictureConfig'] = _PICTURECONFIG
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['PicturePointers'] = _PICTUREPOINTERS
DESCRIPTOR.message_types_by_name['Picture'] = _PICTURE
DESCRIPTOR.message_types_by_name['PicturePointer'] = _PICTUREPOINTER
DESCRIPTOR.enum_types_by_name['DataFormat'] = _DATAFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PictureConfig = _reflection.GeneratedProtocolMessageType('PictureConfig', (_message.Message,), {
  'DESCRIPTOR' : _PICTURECONFIG,
  '__module__' : 'proto.cameraservice.cameraservice_pb2'
  # @@protoc_insertion_point(class_scope:PictureConfig)
  })
_sym_db.RegisterMessage(PictureConfig)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.cameraservice.cameraservice_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

PicturePointers = _reflection.GeneratedProtocolMessageType('PicturePointers', (_message.Message,), {
  'DESCRIPTOR' : _PICTUREPOINTERS,
  '__module__' : 'proto.cameraservice.cameraservice_pb2'
  # @@protoc_insertion_point(class_scope:PicturePointers)
  })
_sym_db.RegisterMessage(PicturePointers)

Picture = _reflection.GeneratedProtocolMessageType('Picture', (_message.Message,), {
  'DESCRIPTOR' : _PICTURE,
  '__module__' : 'proto.cameraservice.cameraservice_pb2'
  # @@protoc_insertion_point(class_scope:Picture)
  })
_sym_db.RegisterMessage(Picture)

PicturePointer = _reflection.GeneratedProtocolMessageType('PicturePointer', (_message.Message,), {
  'DESCRIPTOR' : _PICTUREPOINTER,
  '__module__' : 'proto.cameraservice.cameraservice_pb2'
  # @@protoc_insertion_point(class_scope:PicturePointer)
  })
_sym_db.RegisterMessage(PicturePointer)



_HARDWARECONTROLLER = _descriptor.ServiceDescriptor(
  name='HardwareController',
  full_name='HardwareController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=369,
  serialized_end=434,
  methods=[
  _descriptor.MethodDescriptor(
    name='TakePicture',
    full_name='HardwareController.TakePicture',
    index=0,
    containing_service=None,
    input_type=_PICTURECONFIG,
    output_type=_PICTURE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HARDWARECONTROLLER)

DESCRIPTOR.services_by_name['HardwareController'] = _HARDWARECONTROLLER


_SERVICECONTROLLER = _descriptor.ServiceDescriptor(
  name='ServiceController',
  full_name='ServiceController',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=437,
  serialized_end=641,
  methods=[
  _descriptor.MethodDescriptor(
    name='TakePicture',
    full_name='ServiceController.TakePicture',
    index=0,
    containing_service=None,
    input_type=_PICTURECONFIG,
    output_type=_PICTUREPOINTER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPicture',
    full_name='ServiceController.GetPicture',
    index=1,
    containing_service=None,
    input_type=_PICTUREPOINTER,
    output_type=_PICTURE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeletePicture',
    full_name='ServiceController.DeletePicture',
    index=2,
    containing_service=None,
    input_type=_PICTUREPOINTER,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllPictures',
    full_name='ServiceController.GetAllPictures',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_PICTUREPOINTERS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICECONTROLLER)

DESCRIPTOR.services_by_name['ServiceController'] = _SERVICECONTROLLER

# @@protoc_insertion_point(module_scope)
