# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/scannerservice/scannerservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import open_vector_format_pb2 as open__vector__format__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/scannerservice/scannerservice.proto',
  package='scannerservice',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)proto/scannerservice/scannerservice.proto\x12\x0escannerservice\x1a\x18open_vector_format.proto\"\x8f\x02\n\x10WorkPlaneMessage\x12;\n\tworkPlane\x18\x01 \x01(\x0b\x32\x1d.open_vector_format.WorkPlaneR\tworkPlane\x12Y\n\rmarkingparams\x18\x02 \x03(\x0b\x32\x33.scannerservice.WorkPlaneMessage.MarkingparamsEntryR\rmarkingparams\x1a\x63\n\x12MarkingparamsEntry\x12\x10\n\x03key\x18\x01 \x01(\x05R\x03key\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32!.open_vector_format.MarkingParamsR\x05value:\x02\x38\x01\"\x07\n\x05\x45mpty\"\x81\x01\n\x0fScanFieldConfig\x12\x1a\n\x08xminimum\x18\x01 \x01(\x03R\x08xminimum\x12\x1a\n\x08xmaximum\x18\x02 \x01(\x03R\x08xmaximum\x12\x1a\n\x08yminimum\x18\x03 \x01(\x03R\x08yminimum\x12\x1a\n\x08ymaximum\x18\x04 \x01(\x03R\x08ymaximum\"&\n\x08Position\x12\x0c\n\x01x\x18\x01 \x01(\x03R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x03R\x01y\"$\n\x04Time\x12\x1c\n\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"M\n\x0cProtoPointer\x12\x12\n\x03URI\x18\x01 \x01(\tH\x00R\x03URI\x12\x1e\n\ttimestamp\x18\x02 \x01(\x03H\x00R\ttimestampB\t\n\x07pointer2\xeb\x01\n\x12HardwareController\x12@\n\x0eJumpToPosition\x12\x18.scannerservice.Position\x1a\x14.scannerservice.Time\x12G\n\rScanWorkPlane\x12 .scannerservice.WorkPlaneMessage\x1a\x14.scannerservice.Time\x12J\n\x10GetHardScanField\x12\x15.scannerservice.Empty\x1a\x1f.scannerservice.ScanFieldConfig2\x94\x03\n\x11ServiceController\x12@\n\x0eJumpToPosition\x12\x18.scannerservice.Position\x1a\x14.scannerservice.Time\x12O\n\rScanWorkPlane\x12 .scannerservice.WorkPlaneMessage\x1a\x1c.scannerservice.ProtoPointer\x12\x45\n\x0fRescanWorkPlane\x12\x1c.scannerservice.ProtoPointer\x1a\x14.scannerservice.Time\x12N\n\x14GetScannedWorkPlanes\x12 .scannerservice.WorkPlaneMessage\x1a\x14.scannerservice.Time\x12U\n\x13GetScannedWorkPlane\x12\x1c.scannerservice.ProtoPointer\x1a .scannerservice.WorkPlaneMessageb\x06proto3'
  ,
  dependencies=[open__vector__format__pb2.DESCRIPTOR,])




_WORKPLANEMESSAGE_MARKINGPARAMSENTRY = _descriptor.Descriptor(
  name='MarkingparamsEntry',
  full_name='scannerservice.WorkPlaneMessage.MarkingparamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='scannerservice.WorkPlaneMessage.MarkingparamsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='key', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='scannerservice.WorkPlaneMessage.MarkingparamsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='value', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=359,
)

_WORKPLANEMESSAGE = _descriptor.Descriptor(
  name='WorkPlaneMessage',
  full_name='scannerservice.WorkPlaneMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workPlane', full_name='scannerservice.WorkPlaneMessage.workPlane', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='workPlane', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='markingparams', full_name='scannerservice.WorkPlaneMessage.markingparams', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='markingparams', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_WORKPLANEMESSAGE_MARKINGPARAMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=359,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='scannerservice.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=368,
)


_SCANFIELDCONFIG = _descriptor.Descriptor(
  name='ScanFieldConfig',
  full_name='scannerservice.ScanFieldConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='xminimum', full_name='scannerservice.ScanFieldConfig.xminimum', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='xminimum', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xmaximum', full_name='scannerservice.ScanFieldConfig.xmaximum', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='xmaximum', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yminimum', full_name='scannerservice.ScanFieldConfig.yminimum', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='yminimum', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ymaximum', full_name='scannerservice.ScanFieldConfig.ymaximum', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='ymaximum', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=500,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='scannerservice.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='scannerservice.Position.x', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='x', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='scannerservice.Position.y', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='y', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=540,
)


_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='scannerservice.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='scannerservice.Time.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='timestamp', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=578,
)


_PROTOPOINTER = _descriptor.Descriptor(
  name='ProtoPointer',
  full_name='scannerservice.ProtoPointer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='URI', full_name='scannerservice.ProtoPointer.URI', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='URI', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='scannerservice.ProtoPointer.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='timestamp', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='pointer', full_name='scannerservice.ProtoPointer.pointer',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=580,
  serialized_end=657,
)

_WORKPLANEMESSAGE_MARKINGPARAMSENTRY.fields_by_name['value'].message_type = open__vector__format__pb2._MARKINGPARAMS
_WORKPLANEMESSAGE_MARKINGPARAMSENTRY.containing_type = _WORKPLANEMESSAGE
_WORKPLANEMESSAGE.fields_by_name['workPlane'].message_type = open__vector__format__pb2._WORKPLANE
_WORKPLANEMESSAGE.fields_by_name['markingparams'].message_type = _WORKPLANEMESSAGE_MARKINGPARAMSENTRY
_PROTOPOINTER.oneofs_by_name['pointer'].fields.append(
  _PROTOPOINTER.fields_by_name['URI'])
_PROTOPOINTER.fields_by_name['URI'].containing_oneof = _PROTOPOINTER.oneofs_by_name['pointer']
_PROTOPOINTER.oneofs_by_name['pointer'].fields.append(
  _PROTOPOINTER.fields_by_name['timestamp'])
_PROTOPOINTER.fields_by_name['timestamp'].containing_oneof = _PROTOPOINTER.oneofs_by_name['pointer']
DESCRIPTOR.message_types_by_name['WorkPlaneMessage'] = _WORKPLANEMESSAGE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ScanFieldConfig'] = _SCANFIELDCONFIG
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['Time'] = _TIME
DESCRIPTOR.message_types_by_name['ProtoPointer'] = _PROTOPOINTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkPlaneMessage = _reflection.GeneratedProtocolMessageType('WorkPlaneMessage', (_message.Message,), {

  'MarkingparamsEntry' : _reflection.GeneratedProtocolMessageType('MarkingparamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _WORKPLANEMESSAGE_MARKINGPARAMSENTRY,
    '__module__' : 'proto.scannerservice.scannerservice_pb2'
    # @@protoc_insertion_point(class_scope:scannerservice.WorkPlaneMessage.MarkingparamsEntry)
    })
  ,
  'DESCRIPTOR' : _WORKPLANEMESSAGE,
  '__module__' : 'proto.scannerservice.scannerservice_pb2'
  # @@protoc_insertion_point(class_scope:scannerservice.WorkPlaneMessage)
  })
_sym_db.RegisterMessage(WorkPlaneMessage)
_sym_db.RegisterMessage(WorkPlaneMessage.MarkingparamsEntry)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.scannerservice.scannerservice_pb2'
  # @@protoc_insertion_point(class_scope:scannerservice.Empty)
  })
_sym_db.RegisterMessage(Empty)

ScanFieldConfig = _reflection.GeneratedProtocolMessageType('ScanFieldConfig', (_message.Message,), {
  'DESCRIPTOR' : _SCANFIELDCONFIG,
  '__module__' : 'proto.scannerservice.scannerservice_pb2'
  # @@protoc_insertion_point(class_scope:scannerservice.ScanFieldConfig)
  })
_sym_db.RegisterMessage(ScanFieldConfig)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'proto.scannerservice.scannerservice_pb2'
  # @@protoc_insertion_point(class_scope:scannerservice.Position)
  })
_sym_db.RegisterMessage(Position)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'proto.scannerservice.scannerservice_pb2'
  # @@protoc_insertion_point(class_scope:scannerservice.Time)
  })
_sym_db.RegisterMessage(Time)

ProtoPointer = _reflection.GeneratedProtocolMessageType('ProtoPointer', (_message.Message,), {
  'DESCRIPTOR' : _PROTOPOINTER,
  '__module__' : 'proto.scannerservice.scannerservice_pb2'
  # @@protoc_insertion_point(class_scope:scannerservice.ProtoPointer)
  })
_sym_db.RegisterMessage(ProtoPointer)


_WORKPLANEMESSAGE_MARKINGPARAMSENTRY._options = None

_HARDWARECONTROLLER = _descriptor.ServiceDescriptor(
  name='HardwareController',
  full_name='scannerservice.HardwareController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=660,
  serialized_end=895,
  methods=[
  _descriptor.MethodDescriptor(
    name='JumpToPosition',
    full_name='scannerservice.HardwareController.JumpToPosition',
    index=0,
    containing_service=None,
    input_type=_POSITION,
    output_type=_TIME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ScanWorkPlane',
    full_name='scannerservice.HardwareController.ScanWorkPlane',
    index=1,
    containing_service=None,
    input_type=_WORKPLANEMESSAGE,
    output_type=_TIME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetHardScanField',
    full_name='scannerservice.HardwareController.GetHardScanField',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SCANFIELDCONFIG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HARDWARECONTROLLER)

DESCRIPTOR.services_by_name['HardwareController'] = _HARDWARECONTROLLER


_SERVICECONTROLLER = _descriptor.ServiceDescriptor(
  name='ServiceController',
  full_name='scannerservice.ServiceController',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=898,
  serialized_end=1302,
  methods=[
  _descriptor.MethodDescriptor(
    name='JumpToPosition',
    full_name='scannerservice.ServiceController.JumpToPosition',
    index=0,
    containing_service=None,
    input_type=_POSITION,
    output_type=_TIME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ScanWorkPlane',
    full_name='scannerservice.ServiceController.ScanWorkPlane',
    index=1,
    containing_service=None,
    input_type=_WORKPLANEMESSAGE,
    output_type=_PROTOPOINTER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RescanWorkPlane',
    full_name='scannerservice.ServiceController.RescanWorkPlane',
    index=2,
    containing_service=None,
    input_type=_PROTOPOINTER,
    output_type=_TIME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetScannedWorkPlanes',
    full_name='scannerservice.ServiceController.GetScannedWorkPlanes',
    index=3,
    containing_service=None,
    input_type=_WORKPLANEMESSAGE,
    output_type=_TIME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetScannedWorkPlane',
    full_name='scannerservice.ServiceController.GetScannedWorkPlane',
    index=4,
    containing_service=None,
    input_type=_PROTOPOINTER,
    output_type=_WORKPLANEMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICECONTROLLER)

DESCRIPTOR.services_by_name['ServiceController'] = _SERVICECONTROLLER

# @@protoc_insertion_point(module_scope)
